"use client"

import { useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { Activity, Award, BarChart3, CheckCircle2, Flame, Target, Trophy, XCircle, Zap } from "lucide-react"
import { Button } from "@/components/ui/button"
import { useAuth } from "@/hooks/use-auth"

type Bucket = { key: string; label: string; attempts: number; averageScore: number; accuracy: number }
type ProgressData = { progress: { total_xp: number; current_streak: number; longest_streak: number; last_study_date: string | null }; achievements: { achievement_key: string; unlocked_at: string }[]; recentXp: { id: string; amount: number; reason: string; created_at: string }[]; analytics: { allTime: { attempts: number; averageScore: number; bestScore: number; correct: number; wrong: number; skipped: number; accuracy: number }; recentScoreTrend: { date: string; percentage: number; quizId: string | null; quizTitle: string }[]; byQuiz: Bucket[]; byCategory: Bucket[]; weakestAreas: Bucket[] } }

const achievementInfo: Record<string, { label: string; description: string }> = {
  first_quiz: { label: "First steps", description: "Completed your first quiz" },
  xp_100: { label: "Century club", description: "Earned 100 XP" },
  streak_7: { label: "Seven-day rhythm", description: "Studied for seven consecutive days" },
  perfect_score: { label: "Perfect paper", description: "Scored 100% on a quiz" },
}
const humanize = (key: string) => key.split("_").map((word) => word[0]?.toUpperCase() + word.slice(1)).join(" ")
const dateLabel = (date: string) => new Date(date).toLocaleDateString("en-IN", { day: "numeric", month: "short" })

function Trend({ points }: { points: ProgressData["analytics"]["recentScoreTrend"] }) {
  if (!points.length) return <div className="flex h-56 items-center justify-center rounded-xl border border-dashed border-border/70 text-sm text-muted-foreground">Complete a quiz to begin your score story.</div>
  const width = 720, height = 220, pad = 24
  const coords = points.map((point, index) => ({ x: pad + (index * (width - pad * 2)) / Math.max(points.length - 1, 1), y: height - pad - (Math.max(0, Math.min(100, point.percentage)) / 100) * (height - pad * 2) }))
  const line = coords.map((point, index) => `${index ? "L" : "M"} ${point.x} ${point.y}`).join(" ")
  return <div className="space-y-2"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Recent quiz score trend" className="h-56 w-full overflow-visible"><line x1={pad} x2={width - pad} y1={height - pad} y2={height - pad} stroke="currentColor" className="text-border" /><line x1={pad} x2={pad} y1={pad} y2={height - pad} stroke="currentColor" className="text-border" /><path d={line} fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" className="text-primary" />{coords.map((point, index) => <circle key={points[index].date + index} cx={point.x} cy={point.y} r="5" fill="currentColor" className="text-accent"><title>{points[index].quizTitle}: {points[index].percentage.toFixed(1)}%</title></circle>)}</svg><div className="flex justify-between px-3 text-[11px] text-muted-foreground"><span>{dateLabel(points[0].date)}</span><span>{dateLabel(points[points.length - 1].date)}</span></div></div>
}

function BucketList({ title, items, empty }: { title: string; items: Bucket[]; empty: string }) {
  return <section className="premium-surface rounded-2xl border border-border/60 p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">{title}</h2><BarChart3 className="h-4 w-4 text-primary" /></div>{items.length ? <div className="space-y-4">{items.slice(0, 5).map((item) => <div key={item.key}><div className="mb-1.5 flex justify-between gap-3 text-sm"><span className="truncate font-medium">{item.label}</span><span className="shrink-0 text-xs text-muted-foreground">{item.accuracy.toFixed(1)}% accuracy</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-gradient-to-r from-primary to-accent transition-all duration-700" style={{ width: `${Math.min(100, Math.max(0, item.accuracy))}%` }} /></div><p className="mt-1 text-[11px] text-muted-foreground">{item.attempts} attempt{item.attempts === 1 ? "" : "s"} · {item.averageScore.toFixed(1)}% average</p></div>)}</div> : <p className="py-5 text-sm text-muted-foreground">{empty}</p>}</section>
}

export default function ProgressPage() {
  const { user, loading: authLoading } = useAuth()
  const router = useRouter()
  const [data, setData] = useState<ProgressData | null>(null)
  const [error, setError] = useState("")
  useEffect(() => {
    if (authLoading) return
    if (!user) { router.replace("/login?redirect=/progress"); return }
    fetch("/api/study/progress").then(async (res) => { if (res.status === 401) { router.replace("/login?redirect=/progress"); return null }; if (!res.ok) throw new Error(); return res.json() }).then((json) => { if (json) setData(json) }).catch(() => setError("We could not load your progress right now."))
  }, [authLoading, user, router])
  const stats = useMemo(() => data?.analytics.allTime, [data])
  if (authLoading || (!data && !error)) return <main className="min-h-[100dvh] bg-gradient-to-br from-primary/5 via-background to-accent/5 px-4 py-12"><div className="mx-auto max-w-6xl space-y-5"><div className="h-28 animate-pulse rounded-3xl bg-muted" /><div className="grid gap-4 sm:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="h-28 animate-pulse rounded-2xl bg-muted" />)}</div></div></main>
  if (error) return <main className="flex min-h-[100dvh] items-center justify-center px-4"><div className="text-center"><XCircle className="mx-auto mb-3 h-10 w-10 text-destructive" /><h1 className="text-lg font-bold">Progress is taking a pause</h1><p className="mt-1 text-sm text-muted-foreground">{error}</p><Button className="mt-5" onClick={() => location.reload()}>Try again</Button></div></main>
  if (!data || !stats) return null
  return <main className="min-h-[100dvh] bg-gradient-to-br from-primary/5 via-background to-accent/5"><div className="mx-auto max-w-6xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.2em] text-primary">Study ledger</p><h1 className="study-display text-4xl font-bold tracking-tight sm:text-5xl">Your progress, in focus.</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground">A clear view of the work you have put in — and the areas worth revisiting next.</p></div><Link href="/profile" className="text-sm font-semibold text-primary hover:underline">Back to profile</Link></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border border-primary/20 bg-primary/10 p-4"><Zap className="mb-5 h-5 w-5 text-primary" /><p className="text-3xl font-bold">{data.progress.total_xp.toLocaleString()}</p><p className="text-xs text-muted-foreground">Total XP</p></div><div className="rounded-2xl border border-orange-500/20 bg-orange-500/10 p-4"><Flame className="mb-5 h-5 w-5 text-orange-600" /><p className="text-3xl font-bold">{data.progress.current_streak}</p><p className="text-xs text-muted-foreground">Current day streak</p></div><div className="rounded-2xl border border-accent/25 bg-accent/10 p-4"><Trophy className="mb-5 h-5 w-5 text-accent" /><p className="text-3xl font-bold">{data.progress.longest_streak}</p><p className="text-xs text-muted-foreground">Longest streak</p></div><div className="rounded-2xl border border-border/60 bg-card p-4"><Target className="mb-5 h-5 w-5 text-primary" /><p className="text-3xl font-bold">{stats.accuracy.toFixed(1)}%</p><p className="text-xs text-muted-foreground">Overall accuracy</p></div></div>
    <div className="grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><section className="premium-surface rounded-2xl border border-border/60 p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold">Score trend</h2><p className="text-xs text-muted-foreground">Your latest quiz attempts</p></div><Activity className="h-5 w-5 text-primary" /></div><Trend points={data.analytics.recentScoreTrend} /></section><section className="premium-surface rounded-2xl border border-border/60 p-5"><h2 className="mb-4 font-bold">At a glance</h2><div className="grid grid-cols-2 gap-3">{[["Attempts", stats.attempts], ["Best score", `${stats.bestScore.toFixed(1)}%`], ["Correct", stats.correct], ["Skipped", stats.skipped]].map(([label, value]) => <div key={label} className="rounded-xl bg-muted/45 p-3"><p className="text-xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div>)}</div><div className="mt-5 rounded-xl border border-border/50 p-3"><p className="text-xs text-muted-foreground">Last study session</p><p className="mt-1 text-sm font-semibold">{data.progress.last_study_date ? new Date(data.progress.last_study_date).toLocaleDateString("en-IN", { dateStyle: "medium" }) : "No sessions yet"}</p></div></section></div>
    <div className="grid gap-6 lg:grid-cols-2"><BucketList title="By quiz" items={data.analytics.byQuiz} empty="Quiz breakdowns appear after your first attempt." /><BucketList title="By category" items={data.analytics.byCategory} empty="Category patterns will emerge as you practise." /></div>
    <div className="grid gap-6 lg:grid-cols-[1fr_1fr]"><BucketList title="Worth another look" items={data.analytics.weakestAreas} empty="No weaker areas identified yet — keep going." /><section className="premium-surface rounded-2xl border border-border/60 p-5"><div className="mb-4 flex items-center gap-2"><Award className="h-5 w-5 text-accent" /><h2 className="font-bold">Achievements</h2></div>{data.achievements.length ? <div className="grid gap-2 sm:grid-cols-2">{data.achievements.map((achievement) => { const info = achievementInfo[achievement.achievement_key] || { label: humanize(achievement.achievement_key), description: "A milestone in your study journey" }; return <div key={achievement.achievement_key} className="flex gap-3 rounded-xl border border-border/50 bg-muted/25 p-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-accent/15 text-accent"><CheckCircle2 className="h-4 w-4" /></div><div><p className="text-sm font-bold">{info.label}</p><p className="text-xs text-muted-foreground">{info.description}</p></div></div> })}</div> : <div className="rounded-xl border border-dashed border-border p-5 text-sm text-muted-foreground">Your first milestone is waiting. Complete a quiz to begin.</div>}</section></div>
    <section className="premium-surface rounded-2xl border border-border/60 p-5"><h2 className="mb-4 font-bold">Recent XP</h2>{data.recentXp.length ? <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data.recentXp.slice(0, 6).map((entry) => <div key={entry.id} className="flex items-center justify-between rounded-xl bg-muted/35 px-3 py-2.5"><div><p className="text-sm font-medium">{entry.reason}</p><p className="text-[11px] text-muted-foreground">{dateLabel(entry.created_at)}</p></div><span className="font-mono text-sm font-bold text-primary">+{entry.amount} XP</span></div>)}</div> : <p className="text-sm text-muted-foreground">XP earned from quizzes and study actions will appear here.</p>}</section>
  </div></main>
}