CREATE TABLE IF NOT EXISTS analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pdf_id UUID NOT NULL REFERENCES pdfs(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL CHECK (event_type IN ('view', 'download')),
  event_key TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_analytics_events_created_type
  ON analytics_events(created_at, event_type);
CREATE INDEX IF NOT EXISTS idx_analytics_events_pdf_created
  ON analytics_events(pdf_id, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_analytics_events_idempotency
  ON analytics_events(event_key) WHERE event_key IS NOT NULL;

ALTER TABLE analytics_events ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION increment_view_count(pdf_id UUID, event_key TEXT DEFAULT NULL)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  inserted_id BIGINT;
  new_count INTEGER;
BEGIN
  INSERT INTO analytics_events(pdf_id, event_type, event_key)
  VALUES (pdf_id, 'view', NULLIF(event_key, ''))
  ON CONFLICT (event_key) WHERE event_key IS NOT NULL DO NOTHING
  RETURNING id INTO inserted_id;

  IF inserted_id IS NULL THEN
    SELECT COALESCE(view_count, 0) INTO new_count FROM pdfs WHERE id = pdf_id;
    RETURN new_count;
  END IF;

  UPDATE pdfs
  SET view_count = COALESCE(view_count, 0) + 1
  WHERE id = pdf_id
  RETURNING view_count INTO new_count;

  IF new_count IS NULL THEN RAISE EXCEPTION 'PDF not found'; END IF;
  RETURN new_count;
END;
$$;

CREATE OR REPLACE FUNCTION increment_download_count(pdf_id UUID, event_key TEXT DEFAULT NULL)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  inserted_id BIGINT;
  new_count INTEGER;
BEGIN
  INSERT INTO analytics_events(pdf_id, event_type, event_key)
  VALUES (pdf_id, 'download', NULLIF(event_key, ''))
  ON CONFLICT (event_key) WHERE event_key IS NOT NULL DO NOTHING
  RETURNING id INTO inserted_id;

  IF inserted_id IS NULL THEN
    SELECT COALESCE(download_count, 0) INTO new_count FROM pdfs WHERE id = pdf_id;
    RETURN new_count;
  END IF;

  UPDATE pdfs
  SET download_count = COALESCE(download_count, 0) + 1
  WHERE id = pdf_id
  RETURNING download_count INTO new_count;

  IF new_count IS NULL THEN RAISE EXCEPTION 'PDF not found'; END IF;
  RETURN new_count;
END;
$$;

REVOKE ALL ON FUNCTION increment_view_count(UUID, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION increment_download_count(UUID, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION increment_view_count(UUID, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION increment_download_count(UUID, TEXT) TO service_role;

CREATE OR REPLACE FUNCTION get_analytics_trends(p_days INTEGER DEFAULT 7)
RETURNS TABLE(event_date DATE, views BIGINT, downloads BIGINT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH days AS (
    SELECT generate_series(
      CURRENT_DATE - (LEAST(GREATEST(COALESCE(p_days, 7), 1), 90) - 1),
      CURRENT_DATE,
      INTERVAL '1 day'
    )::DATE AS event_date
  ),
  counts AS (
    SELECT
      (created_at AT TIME ZONE 'UTC')::DATE AS event_date,
      COUNT(*) FILTER (WHERE event_type = 'view') AS views,
      COUNT(*) FILTER (WHERE event_type = 'download') AS downloads
    FROM analytics_events
    WHERE created_at >= (CURRENT_DATE - (LEAST(GREATEST(COALESCE(p_days, 7), 1), 90) - 1))::TIMESTAMP AT TIME ZONE 'UTC'
    GROUP BY (created_at AT TIME ZONE 'UTC')::DATE
  )
  SELECT days.event_date, COALESCE(counts.views, 0), COALESCE(counts.downloads, 0)
  FROM days
  LEFT JOIN counts USING (event_date)
  ORDER BY days.event_date;
$$;

REVOKE ALL ON FUNCTION get_analytics_trends(INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION get_analytics_trends(INTEGER) TO service_role;