CREATE TABLE IF NOT EXISTS audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL CHECK (action IN ('created', 'updated', 'deleted')),
  resource_type TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  actor_type TEXT NOT NULL CHECK (actor_type IN ('user', 'server', 'system')),
  summary TEXT NOT NULL CHECK (char_length(summary) <= 300),
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_events_id_desc ON audit_events(id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_resource ON audit_events(resource_type, id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_action ON audit_events(action, id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_created_at ON audit_events(created_at DESC);

ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION capture_audit_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  row_data JSONB;
  previous_data JSONB;
  record_action TEXT;
  record_id TEXT;
  record_summary TEXT;
  request_role TEXT;
  record_actor TEXT;
  changed_fields JSONB := '[]'::JSONB;
BEGIN
  row_data := CASE WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
  previous_data := CASE WHEN TG_OP = 'UPDATE' THEN to_jsonb(OLD) ELSE NULL END;
  record_action := CASE TG_OP WHEN 'INSERT' THEN 'created' WHEN 'UPDATE' THEN 'updated' ELSE 'deleted' END;
  record_id := COALESCE(row_data->>'id', row_data->>'key', 'unknown');
  record_summary := LEFT(CASE TG_TABLE_NAME
    WHEN 'pdfs' THEN COALESCE(row_data->>'title', 'PDF ' || record_id)
    WHEN 'categories' THEN COALESCE(row_data->>'name', 'Category ' || record_id)
    WHEN 'quizzes' THEN COALESCE(row_data->>'title', 'Quiz ' || record_id)
    WHEN 'folders' THEN COALESCE(row_data->>'name', 'Folder ' || record_id)
    WHEN 'content_folders' THEN COALESCE(row_data->>'name', 'Content folder ' || record_id)
    WHEN 'content_sections' THEN COALESCE(row_data->>'title', 'Content section ' || record_id)
    WHEN 'site_settings' THEN 'Site setting'
    ELSE INITCAP(REPLACE(TG_TABLE_NAME, '_', ' ')) || ' ' || record_id
  END, 300);

  request_role := COALESCE(current_setting('request.jwt.claim.role', true), '');
  record_actor := CASE
    WHEN request_role = 'authenticated' THEN 'user'
    WHEN request_role = 'service_role' THEN 'server'
    ELSE 'system'
  END;

  IF TG_OP = 'UPDATE' THEN
    SELECT COALESCE(jsonb_agg(key ORDER BY key), '[]'::JSONB)
    INTO changed_fields
    FROM jsonb_object_keys(row_data) AS fields(key)
    WHERE row_data->key IS DISTINCT FROM previous_data->key;
  END IF;

  INSERT INTO audit_events(action, resource_type, resource_id, actor_type, summary, metadata)
  VALUES (
    record_action,
    TG_TABLE_NAME,
    record_id,
    record_actor,
    record_summary,
    CASE WHEN TG_OP = 'UPDATE' THEN jsonb_build_object('changed_fields', changed_fields) ELSE '{}'::JSONB END
  );

  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'pdfs', 'categories', 'reviews', 'quizzes', 'folders',
    'site_settings', 'content_folders', 'content_sections',
    'apx_platforms', 'apx_test_series', 'apx_tests', 'apx_questions'
  ]
  LOOP
    IF to_regclass('public.' || table_name) IS NOT NULL THEN
      EXECUTE format('DROP TRIGGER IF EXISTS audit_%I_changes ON public.%I', table_name, table_name);
      EXECUTE format(
        'CREATE TRIGGER audit_%I_changes AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.capture_audit_event()',
        table_name,
        table_name
      );
    END IF;
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION purge_expired_audit_events(retention_days INTEGER DEFAULT 365)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  deleted_count BIGINT;
BEGIN
  DELETE FROM audit_events
  WHERE created_at < NOW() - MAKE_INTERVAL(days => LEAST(GREATEST(COALESCE(retention_days, 365), 30), 3650));
  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$;

REVOKE ALL ON TABLE audit_events FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION capture_audit_event() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION purge_expired_audit_events(INTEGER) FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT ON TABLE audit_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE audit_events_id_seq TO service_role;
GRANT EXECUTE ON FUNCTION purge_expired_audit_events(INTEGER) TO service_role;

CREATE EXTENSION IF NOT EXISTS pg_cron;
DO $$
DECLARE
  existing_job BIGINT;
BEGIN
  SELECT jobid INTO existing_job FROM cron.job WHERE jobname = 'purge-expired-audit-events';
  IF existing_job IS NOT NULL THEN PERFORM cron.unschedule(existing_job); END IF;
  PERFORM cron.schedule(
    'purge-expired-audit-events',
    '17 3 * * *',
    'SELECT public.purge_expired_audit_events(365)'
  );
END;
$$;